# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILwpa9nOaLy4WVYjaJ8W06bx8yxOReMz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Dataset Load**"""

df = pd.read_csv('customers-100.csv')

df.head()

print("Shape:", df.shape)

df.info()

df.describe()

df.isnull().sum()

(df.isnull().sum()/len(df))*100

"""**Duplicate Records**"""

print("Duplicate Rows:", df.duplicated().sum())

df = df.drop_duplicates()

df.duplicated().sum()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

print(df.head())

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print(df.head())

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

print(df.head())

df.sample(5)

print(df.duplicated().sum())

for col in cat_cols:
    df[col] = df[col].astype(str).str.strip()

df.head()

print("Missing Values")

print(df.isnull().sum())

print("\nDuplicates")

print(df.duplicated().sum())

df.to_csv("cleaned_dataset.csv", index=False)

from google.colab import files

files.download("cleaned_dataset.csv")

df.isnull().sum().plot(kind='bar')

plt.title("Missing Values After Cleaning")

plt.show()

import matplotlib.pyplot as plt

df['Country'].value_counts().head(10).plot(kind='bar')

plt.title("Top 10 Countries")
plt.xlabel("Country")
plt.ylabel("Count")
plt.show()

df['City'].value_counts().head(10).plot(kind='bar')

plt.title("Top 10 Cities")
plt.xlabel("City")
plt.ylabel("Count")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
sns.heatmap(df.isnull(), cbar=False)

plt.title("Missing Values Heatmap")
plt.show()

df.dtypes.value_counts().plot(kind='pie', autopct='%1.1f%%')

plt.title("Data Types Distribution")
plt.ylabel("")
plt.show()

df['Company'].value_counts().head(10).plot(kind='barh')

plt.title("Top Companies")
plt.xlabel("Count")
plt.show()

df['City'] = df['City'].str.lower()
df['City'] = df['City'].str.strip()

df.head()

df["First Name"] = df["First Name"].str.strip().str.title()
df["Last Name"] = df["Last Name"].str.strip().str.title()

df.head()

df.to_csv("cleaned_customers.csv", index=False)

print("\nCleaned dataset saved as 'cleaned_customers.csv'")